class AddIndexesToSalaryItems < ActiveRecord::Migration
  def change
    add_index :salary_items, :salary_deserve
    add_index :salary_items, :annual_reward
    add_index :salary_items, :pension_personal
    add_index :salary_items, :pension_margin_personal
    add_index :salary_items, :unemployment_personal
    add_index :salary_items, :unemployment_margin_personal
    add_index :salary_items, :medical_personal
    add_index :salary_items, :medical_margin_personal
    add_index :salary_items, :house_accumulation_personal
    add_index :salary_items, :big_amount_personal
    add_index :salary_items, :income_tax
    add_index :salary_items, :salary_card_addition
    add_index :salary_items, :medical_scan_addition
    add_index :salary_items, :physical_exam_addition
    add_index :salary_items, :total_personal
    add_index :salary_items, :salary_in_fact
    add_index :salary_items, :pension_company
    add_index :salary_items, :pension_margin_company
    add_index :salary_items, :unemployment_company
    add_index :salary_items, :unemployment_margin_company
    add_index :salary_items, :medical_company
    add_index :salary_items, :medical_margin_company
    add_index :salary_items, :injury_company
    add_index :salary_items, :injury_margin_company
    add_index :salary_items, :birth_company
    add_index :salary_items, :birth_margin_company
    add_index :salary_items, :accident_company
    add_index :salary_items, :house_accumulation_company
    add_index :salary_items, :total_company
    add_index :salary_items, :social_insurance_to_salary_deserve
    add_index :salary_items, :medical_insurance_to_salary_deserve
    add_index :salary_items, :house_accumulation_to_salary_deserve
    add_index :salary_items, :social_insurance_to_pre_deduct
    add_index :salary_items, :medical_insurance_to_pre_deduct
    add_index :salary_items, :house_accumulation_to_pre_deduct
    add_index :salary_items, :transfer_fund_to_person
    add_index :salary_items, :transfer_fund_to_account
    add_index :salary_items, :admin_amount
    add_index :salary_items, :total_sum
    add_index :salary_items, :total_sum_with_admin_amount
    add_index :salary_items, :remark
    add_index :salary_items, :created_at
    add_index :salary_items, :updated_at
    add_index :salary_items, :deduct_addition
    add_index :salary_items, :salary_deduct_addition
    add_index :salary_items, :other_deduct_addition
    add_index :salary_items, :other_personal
    add_index :salary_items, :other_company
  end
end
