class AddSalaryTableAssocIndexToSalaryItems < ActiveRecord::Migration
  def change
    add_index :salary_items, [:salary_table_id, :salary_deserve], name: 'idx_on_st_and_salary_deserve'
    add_index :salary_items, [:salary_table_id, :annual_reward], name: 'idx_on_st_and_annual_reward'
    add_index :salary_items, [:salary_table_id, :pension_personal], name: 'idx_on_st_and_pension_personal'
    add_index :salary_items, [:salary_table_id, :pension_margin_personal], name: 'idx_on_st_and_pension_margin_personal'
    add_index :salary_items, [:salary_table_id, :unemployment_personal], name: 'idx_on_st_and_unemployment_personal'
    add_index :salary_items, [:salary_table_id, :unemployment_margin_personal], name: 'idx_on_st_and_unemployment_margin_personal'
    add_index :salary_items, [:salary_table_id, :medical_personal], name: 'idx_on_st_and_medical_personal'
    add_index :salary_items, [:salary_table_id, :medical_margin_personal], name: 'idx_on_st_and_medical_margin_personal'
    add_index :salary_items, [:salary_table_id, :house_accumulation_personal], name: 'idx_on_st_and_house_accumulation_personal'
    add_index :salary_items, [:salary_table_id, :big_amount_personal], name: 'idx_on_st_and_big_amount_personal'
    add_index :salary_items, [:salary_table_id, :income_tax], name: 'idx_on_st_and_income_tax'
    add_index :salary_items, [:salary_table_id, :salary_card_addition], name: 'idx_on_st_and_salary_card_addition'
    add_index :salary_items, [:salary_table_id, :medical_scan_addition], name: 'idx_on_st_and_medical_scan_addition'
    add_index :salary_items, [:salary_table_id, :physical_exam_addition], name: 'idx_on_st_and_physical_exam_addition'
    add_index :salary_items, [:salary_table_id, :total_personal], name: 'idx_on_st_and_total_personal'
    add_index :salary_items, [:salary_table_id, :salary_in_fact], name: 'idx_on_st_and_salary_in_fact'
    add_index :salary_items, [:salary_table_id, :pension_company], name: 'idx_on_st_and_pension_company'
    add_index :salary_items, [:salary_table_id, :pension_margin_company], name: 'idx_on_st_and_pension_margin_company'
    add_index :salary_items, [:salary_table_id, :unemployment_company], name: 'idx_on_st_and_unemployment_company'
    add_index :salary_items, [:salary_table_id, :unemployment_margin_company], name: 'idx_on_st_and_unemployment_margin_company'
    add_index :salary_items, [:salary_table_id, :medical_company], name: 'idx_on_st_and_medical_company'
    add_index :salary_items, [:salary_table_id, :medical_margin_company], name: 'idx_on_st_and_medical_margin_company'
    add_index :salary_items, [:salary_table_id, :injury_company], name: 'idx_on_st_and_injury_company'
    add_index :salary_items, [:salary_table_id, :injury_margin_company], name: 'idx_on_st_and_injury_margin_company'
    add_index :salary_items, [:salary_table_id, :birth_company], name: 'idx_on_st_and_birth_company'
    add_index :salary_items, [:salary_table_id, :birth_margin_company], name: 'idx_on_st_and_birth_margin_company'
    add_index :salary_items, [:salary_table_id, :accident_company], name: 'idx_on_st_and_accident_company'
    add_index :salary_items, [:salary_table_id, :house_accumulation_company], name: 'idx_on_st_and_house_accumulation_company'
    add_index :salary_items, [:salary_table_id, :total_company], name: 'idx_on_st_and_total_company'
    add_index :salary_items, [:salary_table_id, :admin_amount], name: 'idx_on_st_and_admin_amount'
    add_index :salary_items, [:salary_table_id, :total_sum], name: 'idx_on_st_and_total_sum'
    add_index :salary_items, [:salary_table_id, :total_sum_with_admin_amount], name: 'idx_on_st_and_total_sum_with_admin_amount'
    add_index :salary_items, [:salary_table_id, :remark], name: 'idx_on_st_and_remark'
    add_index :salary_items, [:salary_table_id, :created_at], name: 'idx_on_st_and_created_at'
    add_index :salary_items, [:salary_table_id, :updated_at], name: 'idx_on_st_and_updated_at'
    add_index :salary_items, [:salary_table_id, :normal_staff_id], name: 'idx_on_st_and_normal_staff_id'
    add_index :salary_items, [:salary_table_id, :deduct_addition], name: 'idx_on_st_and_deduct_addition'
    add_index :salary_items, [:salary_table_id, :salary_deduct_addition], name: 'idx_on_st_and_salary_deduct_addition'
    add_index :salary_items, [:salary_table_id, :other_deduct_addition], name: 'idx_on_st_and_other_deduct_addition'
    add_index :salary_items, [:salary_table_id, :other_personal], name: 'idx_on_st_and_other_personal'
    add_index :salary_items, [:salary_table_id, :other_company], name: 'idx_on_st_and_other_company'
    add_index :salary_items, [:salary_table_id, :role], name: 'idx_on_st_and_role'
  end
end
